In [9]:
import pickle
import numpy as np 

In [10]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [11]:
# Assume user input 
# places / gender /age / SibSb / Parch / Fare / Embarked 
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [12]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [16]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [17]:
test_input_sex

array([[0., 1.]])

In [19]:
test_input_embarked = ohe_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [20]:
test_input_embarked

array([[0., 0., 1.]])

In [24]:
test_input_age = test_input[:,2].reshape(1,1)

In [32]:
test_input_transformed = np.concatenate((test_input[:,[3,4,5]],test_input_age,test_input_age, test_input_sex,test_input_embarked),axis = 1 )


In [ ]:
test_inputtransformed.shape

(1, 10)

In [34]:
clf.predict(test_input_transformed)

array([0])