# Numpy 
* Creating Numpy array 

In [3]:
import numpy as np 

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
# 2D array 
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# dtype 
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
# with reshape 

np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# np.ones and np.zeros 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.random.random((3,4))

array([[0.93710771, 0.57284799, 0.01406188, 0.93915104],
       [0.21742862, 0.01952677, 0.78980681, 0.56729737],
       [0.195454  , 0.0381801 , 0.36080894, 0.27792991]])

In [ ]:
# np.linspace (linear space )
np.linspace(-10 , 10 ,10 )

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [20]:
# np.identity 
np.identity(3 , dtype = int )

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Array Atributes 

In [24]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float ).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
# ndim 
a1.ndim

1

In [28]:

a2.ndim

2

In [ ]:
# shape
a2.shape 

(3, 4)

In [30]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [31]:
# Size 
a2.size

12

In [33]:
# itemsize
a1.itemsize

8

In [34]:
# dtype 
a1.dtype

dtype('int64')

# Changing Datatype 

In [37]:
# astype 
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [41]:
# Scalar Operations 

# arithmetic 
a1 *2 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
# relational operation 

a2 > 17 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
# vector Operaton 
# arithmetic Operation  
a1 + a2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function 

In [48]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[82., 28., 71.],
       [55., 13., 44.],
       [ 1., 29., 67.]])

In [49]:
# max/min/sum/prod 
np.prod(a2)

np.int64(647647525324800)

In [50]:
np.max(a1,axis = 1 )

array([82., 55., 67.])

In [52]:
# mean/median/std/var
np.median(a1 , axis=1 )

array([71., 44., 29.])

In [53]:
#trigonometric functions 
np.sin(a1)

array([[ 0.31322878,  0.27090579,  0.95105465],
       [-0.99975517,  0.42016704,  0.01770193],
       [ 0.84147098, -0.66363388, -0.85551998]])

In [58]:
# dot proudct 

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
# log and exponents 
np.exp(a1)
np.log(a2)

In [64]:
# round/floor/ceil
c = np.random.random((3,3))*100
c

array([[ 6.84474453, 13.14213869,  3.78880699],
       [96.83163681, 42.27905347, 41.24470053],
       [72.79431013, 86.997233  , 34.96555681]])

In [65]:
np.round(c)

array([[ 7., 13.,  4.],
       [97., 42., 41.],
       [73., 87., 35.]])

In [66]:
np.floor(c)

array([[ 6., 13.,  3.],
       [96., 42., 41.],
       [72., 86., 34.]])

In [67]:
np.ceil(c)

array([[ 7., 14.,  4.],
       [97., 43., 42.],
       [73., 87., 35.]])

# Indexing and Slicing

In [70]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [71]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a1[9]

np.int64(9)

In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2] # [row,coloumn]

np.int64(6)

In [78]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1] # [matrix , coloumn , row ]

np.int64(5)

In [83]:
a3[0,1,1]

np.int64(3)

In [85]:
# Slicing 
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a1[2:5] # [start ,stop , interval ]

array([2, 3, 4])

In [88]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [89]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [94]:
a2[0,:]

array([0, 1, 2, 3])

In [95]:
a2[:,2]

array([ 2,  6, 10])

In [96]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,1::2] # [start:End:Interval] [coloumn , row ]

array([[ 1,  3],
       [ 9, 11]])

In [118]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [206]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [201]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [202]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [203]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [204]:
a3[0,1,:]

array([3, 4, 5])

In [205]:
a3[1,:,1] # : iska matlab sara 

array([10, 13, 16])

# Iterating 

In [211]:
a1
for i in a1 :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [212]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [215]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [217]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping 

In [ ]:
# Reshape 

In [218]:
# Transpose 
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2) # a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# Ravel changes any array to 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking
* Horizotal 
* Vertical 

In [223]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [224]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [227]:
a6 = np.hstack((a4,a5))
a6

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [228]:
a7 = np.vstack((a4,a5))
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [232]:
np.vsplit(a7,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [233]:
np.hsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]